name: Go

on:
  push:
    branches: ICE-GB-action

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        cd build
        ./init.sh

    - name: Build
      run: |
        cd build
        ./build-all.sh
